# Generated by Django 4.0 on 2023-08-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='pv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='e3zaAzYXph', max_length=20, unique=True),
        ),
    ]
